from google.generativeai.types import HarmCategory, HarmBlockThreshold
safety_settings = {
    HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
    HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
}

import os
import google.generativeai as genai


# Create the model
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 40,
  "max_output_tokens": 8192,
  "response_mime_type": "text/plain",
}
genai.configure(api_key="AIzaSyBeBKUl5kF_HrhmgxFqyYLsMPpUmj9Frmg")

model = genai.GenerativeModel(
  model_name="gemini-2.0-flash-exp",
  generation_config=generation_config,
)


def prompt_response(prompt):
  response = model.generate_content([
    "input: Variant Question",
    "output: Bot Response",
    "input: សួស្តី",
    "output: សួស្តី! សូមស្វាគមន៍មកកាន់ផ្នែកទំនាក់ទំនងសេវាកម្មអតិថិជន អេ​ អឹម ខេ។\nខ្ញុំគឺអេ អឹម ខេ ឆាតបូត 💬 តើមានអ្វីអាចខាងខ្ញុំជួយបាន?\n(សូមចុចប៊ូតុង “ជួបបុគ្គលិក” នៅខាងក្រោយគេបំផុតសំរាប់បញ្ហាបច្ចេកទេសផ្សេងៗ)",
    "input: ហេ",
    "output: សួស្តី! សូមស្វាគមន៍មកកាន់ផ្នែកទំនាក់ទំនងសេវាកម្មអតិថិជន អេ​ អឹម ខេ។\nខ្ញុំគឺអេ អឹម ខេ ឆាតបូត 💬 តើមានអ្វីអាចខាងខ្ញុំជួយបាន?\n(សូមចុចប៊ូតុង “ជួបបុគ្គលិក” នៅខាងក្រោយគេបំផុតសំរាប់បញ្ហាបច្ចេកទេសផ្សេងៗ)",
    "input: ហាឡូ",
    "output: សួស្តី! សូមស្វាគមន៍មកកាន់ផ្នែកទំនាក់ទំនងសេវាកម្មអតិថិជន អេ​ អឹម ខេ។\nខ្ញុំគឺអេ អឹម ខេ ឆាតបូត 💬 តើមានអ្វីអាចខាងខ្ញុំជួយបាន?\n(សូមចុចប៊ូតុង “ជួបបុគ្គលិក” នៅខាងក្រោយគេបំផុតសំរាប់បញ្ហាបច្ចេកទេសផ្សេងៗ)",
    "input: ហាយ",
    "output: សួស្តី! សូមស្វាគមន៍មកកាន់ផ្នែកទំនាក់ទំនងសេវាកម្មអតិថិជន អេ​ អឹម ខេ។\nខ្ញុំគឺអេ អឹម ខេ ឆាតបូត 💬 តើមានអ្វីអាចខាងខ្ញុំជួយបាន?\n(សូមចុចប៊ូតុង “ជួបបុគ្គលិក” នៅខាងក្រោយគេបំផុតសំរាប់បញ្ហាបច្ចេកទេសផ្សេងៗ)",
    "input: ចង់ក្លាយជាភ្នាក់ងារ",
    "output: ជម្រាបសួរបង!\nអរគុណចំពោះការចាប់អារម្មណ៍!🙏\nសម្រាប់លក្ខខណ្ឌដើម្បីក្លាយជាភ្នាក់ងារ អេ អឹម ខេ គឺ\n⏱️មានពេលវេលាគ្រប់គ្រាន់ដើម្បីផ្តល់សេវាជូនអតិថិជន\n📍មានទីតាំងសរម្យ\n✍️ចេះអាន សរសេរ និងប្រើប្រាស់ទូរស័ព្ទដៃទំនើប\n💲មានដើមទុនគ្រប់គ្រាន់\nដើម្បីយើងខ្ញុំងាយផ្តល់ព័ត៌មានលម្អិតជូនបង សូមអនុញ្ញាត្តិស្គាល់\n📞លេខទូរស័ព្ទរបស់បងផង!",
    "input: ក្លាយជាភ្នាក់ងារ",
    "output: ជម្រាបសួរបង!\nអរគុណចំពោះការចាប់អារម្មណ៍!🙏\nសម្រាប់លក្ខខណ្ឌដើម្បីក្លាយជាភ្នាក់ងារ អេ អឹម ខេ គឺ\n⏱️មានពេលវេលាគ្រប់គ្រាន់ដើម្បីផ្តល់សេវាជូនអតិថិជន\n📍មានទីតាំងសរម្យ\n✍️ចេះអាន សរសេរ និងប្រើប្រាស់ទូរស័ព្ទដៃទំនើប\n💲មានដើមទុនគ្រប់គ្រាន់\nដើម្បីយើងខ្ញុំងាយផ្តល់ព័ត៌មានលម្អិតជូនបង សូមអនុញ្ញាត្តិស្គាល់\n📞លេខទូរស័ព្ទរបស់បងផង!",
    "input: ចង់បង់រំលស់ឡាន",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: ចង់ទិញឡានបង់រំលស់",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: ម៉ូតូអគ្គសនី",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: ឡានអគ្គសនី",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: ឡជីឧស្ម័ន",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: ទិញសូឡា",
    "output: សួស្តីបង! អេ អឹម ខេមានសេវាបង់រំលស់រថយន្ត សម្រាប់ការប្រើប្រាស់ក្នុងគ្រួសារ បានទាំងអ្នកធ្វើការ និងអ្នករកស៊ី។ តើបងចង់បង់រំលស់រថយន្តថ្មី ឬមួយទឹកក្រដាសពន្ធ ឬស្លាក់លេខ?",
    "input: បើកដំណើរការគណនី",
    "output: សួស្តីបង! បងអាចស្នើសុំបើកដំណើរការគណនីដែលអសកម្ម តាមរយៈកម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត អេ អឹម ខេបាន។\n\nតើអ្នកកំពុងចូលប្រើប្រាស់កម្មវិធីធនាគាចល័ត (Log In) ឬមិនទាន់ចូល (Non-Log In)?",
    "input: គណនីអសកម្ម",
    "output: សួស្តីបង! បងអាចស្នើសុំបើកដំណើរការគណនីដែលអសកម្ម តាមរយៈកម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត អេ អឹម ខេបាន។\n\nតើអ្នកកំពុងចូលប្រើប្រាស់កម្មវិធីធនាគាចល័ត (Log In) ឬមិនទាន់ចូល (Non-Log In)?",
    "input: ចង់ផ្លាស់ប្តូរលេខទូរស័ព្ទ",
    "output: សួស្តី! បងស្នើសុំ អេ អឹម ខេ​ផ្លាស់ប្តូរលេខទូរស័ព្ទតាមអនឡាញបាន តែតម្រូវបងស្នើសុំតាមឆាតក្នុងកម្មវីធីធនាគារចល័ត អេ អឹម ខេ៖\n\nតើអ្នកកំពុងឆាតពីកម្មវិធីអ្វីដែរ?",
    "input: ចង់ប្តូរលេខទូរស័ព្ទព្រោះបាត់លេខចាស់",
    "output: សួស្តី! បងស្នើសុំ អេ អឹម ខេ​ផ្លាស់ប្តូរលេខទូរស័ព្ទតាមអនឡាញបាន តែតម្រូវបងស្នើសុំតាមឆាតក្នុងកម្មវីធីធនាគារចល័ត អេ អឹម ខេ៖\n\nតើអ្នកកំពុងឆាតពីកម្មវិធីអ្វីដែរ?",
    "input: ស្នើសុំលេខគណនីពិសេស",
    "output: សួស្តី! បងស្នើសុំ អេ អឹម ខេ​ផ្លាស់ប្តូរលេខគណនីធម្មតាទៅជាលេខពិសេស(ទម្រង់លេខទូរស័ព្ទ) តាមអនឡាញបាន តែតម្រូវបងស្នើសុំតាមឆាតក្នុងកម្មវីធីធនាគារចល័ត អេ អឹម ខេ៖\n\nតើបងកំពុងឆាតលើកម្មវិធីអ្វីដែរ?",
    "input: ចង់ប្តូរលេខពិសេសេ",
    "output: សួស្តី! បងស្នើសុំ អេ អឹម ខេ​ផ្លាស់ប្តូរលេខគណនីធម្មតាទៅជាលេខពិសេស(ទម្រង់លេខទូរស័ព្ទ) តាមអនឡាញបាន តែតម្រូវបងស្នើសុំតាមឆាតក្នុងកម្មវីធីធនាគារចល័ត អេ អឹម ខេ៖\n\nតើបងកំពុងឆាតលើកម្មវិធីអ្វីដែរ?",
    "input: សន្សំប្រាក់",
    "output: សូមអរគុណសម្រាប់ការចាប់អារម្មណ៍ផលិតផលសន្សំអេអឹមខេ។\n\nអេ អឹម ខេ មានគណនីសន្សំច្រើនប្រភេទសូមបងជ្រើសរើសដូចខាងក្រោម៖",
    "input: សន្សំសំចៃ",
    "output: សូមអរគុណសម្រាប់ការចាប់អារម្មណ៍ផលិតផលសន្សំអេអឹមខេ។\n\nអេ អឹម ខេ មានគណនីសន្សំច្រើនប្រភេទសូមបងជ្រើសរើសដូចខាងក្រោម៖",
    "input: គណនីសន្សំ",
    "output: សូមអរគុណសម្រាប់ការចាប់អារម្មណ៍ផលិតផលសន្សំអេអឹមខេ។\n\nអេ អឹម ខេ មានគណនីសន្សំច្រើនប្រភេទសូមបងជ្រើសរើសដូចខាងក្រោម៖",
    "input: សន្សំលុយ",
    "output: សូមអរគុណសម្រាប់ការចាប់អារម្មណ៍ផលិតផលសន្សំអេអឹមខេ។\n\nអេ អឹម ខេ មានគណនីសន្សំច្រើនប្រភេទសូមបងជ្រើសរើសដូចខាងក្រោម៖",
    "input: បើកប្រាក់ខែ",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏បើកប្រាក់បៀវត្ស៍ (បើកប្រាក់ខែ)\n\nដូចនេះសូមបងផ្តល់ព័ត៌មានមួយចំនួន ដើម្បីប្អូននឹងបញ្ជូនទៅកាន់បុគ្គលិកដើម្បីទាក់ទងទៅបងវិញ សូមបងផ្តល់មួចំនួនដូចខាងក្រោម៖\n\nតើក្រុមហ៊ុនរបស់បងមានឈ្មោះអ្វី?",
    "input: សេវាបើកប្រាក់បៀវត្ស",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏បើកប្រាក់បៀវត្ស៍ (បើកប្រាក់ខែ)\n\nដូចនេះសូមបងផ្តល់ព័ត៌មានមួយចំនួន ដើម្បីប្អូននឹងបញ្ជូនទៅកាន់បុគ្គលិកដើម្បីទាក់ទងទៅបងវិញ សូមបងផ្តល់មួចំនួនដូចខាងក្រោម៖\n\nតើក្រុមហ៊ុនរបស់បងមានឈ្មោះអ្វី?",
    "input: ធានារ៉ាប់រង់",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏ផលិផលធានារ៉ាប់រង់របស់ អេអឹមខេមានផលិតផលធានារ៉ាប់រង២ប្រភេទខាងក្រោមនេះ\n\n១. សេវាធានារ៉ាប់រងអាយុជីវិតខ្នាតតូច\n\n២. ធានារ៉ាប់រងអាយុជីវិតដាយអិឈិ\n\nតើបងចាប់អារម្មណ៍មួយណាដែរ?",
    "input: ចង់ទិញធានារ៉ាប់រង់",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏ផលិផលធានារ៉ាប់រង់របស់ អេអឹមខេមានផលិតផលធានារ៉ាប់រង២ប្រភេទខាងក្រោមនេះ\n\n១. សេវាធានារ៉ាប់រងអាយុជីវិតខ្នាតតូច\n\n២. ធានារ៉ាប់រងអាយុជីវិតដាយអិឈិ\n\nតើបងចាប់អារម្មណ៍មួយណាដែរ?",
    "input: ធានារ៉ាប់រង់អាយុជីវិត",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏ផលិផលធានារ៉ាប់រង់របស់ អេអឹមខេមានផលិតផលធានារ៉ាប់រង២ប្រភេទខាងក្រោមនេះ\n\n១. សេវាធានារ៉ាប់រងអាយុជីវិតខ្នាតតូច\n\n២. ធានារ៉ាប់រងអាយុជីវិតដាយអិឈិ\n\nតើបងចាប់អារម្មណ៍មួយណាដែរ?",
    "input: ធានារ៉ាប់ខ្នាតតូច",
    "output: សួស្តី! អរគុណសំរាប់ការចាប់អារម្មណ៏ផលិផលធានារ៉ាប់រង់របស់ អេអឹមខេមានផលិតផលធានារ៉ាប់រង២ប្រភេទខាងក្រោមនេះ\n\n១. សេវាធានារ៉ាប់រងអាយុជីវិតខ្នាតតូច\n\n២. ធានារ៉ាប់រងអាយុជីវិតដាយអិឈិ\n\nតើបងចាប់អារម្មណ៍មួយណាដែរ?",
    "input: ម៉ោងធ្វើការ",
    "output: សួស្តីបង! សម្រាប់ម៉ោង និងថ្ងៃបម្រើសេវាកម្មរបស់ការិយាល័យ អេ អឹម ខេ គឺពីម៉ោង ៨៖០០ព្រឹក ដល់ ម៉ោង ៣៖៣០ល្ងាច ចាប់ពីថ្ងៃច័ន្ទ ដល់ថ្ងៃសុក្រ (លើកលែងថ្ងៃបុណ្យជាតិ)។",
    "input: តើម៉ោងធ្វើការអេអឹមខេពេលណាខ្លះ",
    "output: សួស្តីបង! សម្រាប់ម៉ោង និងថ្ងៃបម្រើសេវាកម្មរបស់ការិយាល័យ អេ អឹម ខេ គឺពីម៉ោង ៨៖០០ព្រឹក ដល់ ម៉ោង ៣៖៣០ល្ងាច ចាប់ពីថ្ងៃច័ន្ទ ដល់ថ្ងៃសុក្រ (លើកលែងថ្ងៃបុណ្យជាតិ)។",
    "input: ដាក់ពាក្យធ្វើការ",
    "output: សូមអរគុណចំពោះការចាប់អារម្មណ៍ឱកាសការងារនៅ អេ អឹម ខេ\n\nសំរាប់ឱកាសការងារ អានព័ត៌មានលម្អិតតាមតំណមួយនេះ\nhttps://www.amkcambodia.com/km/ឱកាសការងារ/\n\nដើម្បីដាក់ពាក្យសូមផ្ញើប្រវត្តិរូបសង្ខេប (CV and Cover Letter) ដោយបញ្ជាក់ពីផ្នែក ឬតួនាទីដែលលោកអ្នកចាប់អារម្មណ៍ទៅតាមបណ្តាញដូចខាងក្រោម:\nអ៊ីម៉ែល: job@amkcambodia.com;\nTelegram: https://t.me/Amkcambodia;\nប្រអប់សារ AMK MFI (AMK Facebook Messenger) or AMK Career.",
    "input: ឱកាសការងារ",
    "output: សូមអរគុណចំពោះការចាប់អារម្មណ៍ឱកាសការងារនៅ អេ អឹម ខេ\n\nសំរាប់ឱកាសការងារ អានព័ត៌មានលម្អិតតាមតំណមួយនេះ\nhttps://www.amkcambodia.com/km/ឱកាសការងារ/\n\nដើម្បីដាក់ពាក្យសូមផ្ញើប្រវត្តិរូបសង្ខេប (CV and Cover Letter) ដោយបញ្ជាក់ពីផ្នែក ឬតួនាទីដែលលោកអ្នកចាប់អារម្មណ៍ទៅតាមបណ្តាញដូចខាងក្រោម:\nអ៊ីម៉ែល: job@amkcambodia.com;\nTelegram: https://t.me/Amkcambodia;\nប្រអប់សារ AMK MFI (AMK Facebook Messenger) or AMK Career.",
    "input: ទីតាំងអេអឹមខេ",
    "output: សូមអរគុណសំរាប់ការចាប់អារម្មណ៏ផលិតផលនិងសេវាកម្មរបស់ អេ អឹម ខេ\nសូមចូលតាមតំណមួយនេះសំរាប់ទីតាំងរបស់ការិយាល័យរបស់ អេ អឹម ខេ និងមាស៊ីន ATM\nhttps://www.amkcambodia.com/km/ទំនាក់ទំនង-2/",
    "input: ទីតាំងការិយាល័យ",
    "output: សូមអរគុណសំរាប់ការចាប់អារម្មណ៏ផលិតផលនិងសេវាកម្មរបស់ អេ អឹម ខេ\nសូមចូលតាមតំណមួយនេះសំរាប់ទីតាំងរបស់ការិយាល័យរបស់ អេ អឹម ខេ និងមាស៊ីន ATM\nhttps://www.amkcambodia.com/km/ទំនាក់ទំនង-2/",
    "input: ទីតាំងម៉ាស៊ីន អេ ធី អឹម",
    "output: សូមអរគុណសំរាប់ការចាប់អារម្មណ៏ផលិតផលនិងសេវាកម្មរបស់ អេ អឹម ខេ\nសូមចូលតាមតំណមួយនេះសំរាប់ទីតាំងរបស់ការិយាល័យរបស់ អេ អឹម ខេ និងមាស៊ីន ATM\nhttps://www.amkcambodia.com/km/ទំនាក់ទំនង-2/",
    "input: ទីតាំងម៉ាស៊ីន ATM",
    "output: សូមអរគុណសំរាប់ការចាប់អារម្មណ៏ផលិតផលនិងសេវាកម្មរបស់ អេ អឹម ខេ\nសូមចូលតាមតំណមួយនេះសំរាប់ទីតាំងរបស់ការិយាល័យរបស់ អេ អឹម ខេ និងមាស៊ីន ATM\nhttps://www.amkcambodia.com/km/ទំនាក់ទំនង-2/",
    "input: ដៃគូអាជីវកម្ម",
    "output: សួស្តីបង! ដៃគូអាជីវកម្ម អេ អឹម ខេ គីសំដៅលើអាជីវករដែលបានអោយអតិថិជនទូទាត់ថ្លៃទំនិញរបស់គាត់តាមរយះ ការស្កេន KHQR របស់ អេ អឹម ខេ ពី App របស់ធនាគារណាក៏បាន។ បើសិនបងចង់ក្លាយជា ដៃគូអាជីវកម្ម អេ អឹម ខេ សូមបងផ្តល់ព័ត៌មានមួយចំនួនដូចខាងក្រោមនេះ៖\nសូមបងផ្តល់លេខទូរស័ព្ទរបស់បង!",
    "input: កាត",
    "output: អតិថិជនរបស់ អេ អឹម ខេ អាចពិនិត្យមើលគណនី និងធ្វើប្រតិបត្តិការផ្សេងរបស់ខ្លួនបានគ្រប់ពេលវេលា ដោយប្រើប្រាស់កាត នៅម៉ាស៊ីន(អេធីអឹម/ស៊ីឌីអឹម) និងភ្នាក់ងារ អេ​ អឹម ខេ។ អេ អឹម ខេ ផ្តល់ជូនកាតចំនួន ៣ ប្រភេទខុសៗគ្នា និងកាតនិមិត្ត Union Pay ។\n\nអតិថិជនក៏អាចដកបានគ្រប់ម៉ាស៊ុន អេ ធី អឹម របស់ស្ថាបនផ្សេងដែលជាសមាជិករបស់ ស៊ីអេសអេស (CSS)។ https://www.amkcambodia.com/km/css-members-kh/",
    "input: អេអឹមខេកាត",
    "output: អតិថិជនរបស់ អេ អឹម ខេ អាចពិនិត្យមើលគណនី និងធ្វើប្រតិបត្តិការផ្សេងរបស់ខ្លួនបានគ្រប់ពេលវេលា ដោយប្រើប្រាស់កាត នៅម៉ាស៊ីន(អេធីអឹម/ស៊ីឌីអឹម) និងភ្នាក់ងារ អេ​ អឹម ខេ។ អេ អឹម ខេ ផ្តល់ជូនកាតចំនួន ៣ ប្រភេទខុសៗគ្នា និងកាតនិមិត្ត Union Pay ។\n\nអតិថិជនក៏អាចដកបានគ្រប់ម៉ាស៊ុន អេ ធី អឹម របស់ស្ថាបនផ្សេងដែលជាសមាជិករបស់ ស៊ីអេសអេស (CSS)។ https://www.amkcambodia.com/km/css-members-kh/",
    "input: កាតអេអឹមខេ",
    "output: អតិថិជនរបស់ អេ អឹម ខេ អាចពិនិត្យមើលគណនី និងធ្វើប្រតិបត្តិការផ្សេងរបស់ខ្លួនបានគ្រប់ពេលវេលា ដោយប្រើប្រាស់កាត នៅម៉ាស៊ីន(អេធីអឹម/ស៊ីឌីអឹម) និងភ្នាក់ងារ អេ​ អឹម ខេ។ អេ អឹម ខេ ផ្តល់ជូនកាតចំនួន ៣ ប្រភេទខុសៗគ្នា និងកាតនិមិត្ត Union Pay ។\n\nអតិថិជនក៏អាចដកបានគ្រប់ម៉ាស៊ុន អេ ធី អឹម របស់ស្ថាបនផ្សេងដែលជាសមាជិករបស់ ស៊ីអេសអេស (CSS)។ https://www.amkcambodia.com/km/css-members-kh/",
    "input: វេរលុយ",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់សេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស និង ក្រៅប្រទេស។\n\nតើបងចង់ដឹងពីសេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស ឬ ក្រៅប្រទេស?",
    "input: ផ្ទេរប្រាក់",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់សេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស និង ក្រៅប្រទេស។\n\nតើបងចង់ដឹងពីសេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស ឬ ក្រៅប្រទេស?",
    "input: ផ្ទេរ",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់សេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស និង ក្រៅប្រទេស។\n\nតើបងចង់ដឹងពីសេវាកម្មផ្ទេរប្រាក់ក្នុងប្រទេស ឬ ក្រៅប្រទេស?",
    "input: អត្រារប្តូរ",
    "output: សួស្តីបង! សម្រាប់អត្រា​ប្តូរប្រាក់​របស់ អេ អឹម ខេ ​នឹង​ផ្លាស់​ប្តូរ​តាម​ពេលវេលា​មួយ​ជា​ទៀង​ទាត់នៅ​រៀង​រាល់​ថ្ងៃ​ធ្វើ​ការ ។ ប្រសិនបើ​លោក​អ្នក​ចង់​ដឹង​អត្រាប្តូរប្រាក់​នា​ថ្ងៃ​កន្លង​មក សូមបងចុចលើតំណរនេះ ៖ https://www.amkcambodia.com/km/អត្រាប្តូរប្រាក់/\n\nសម្គាល់៖ អត្រាប្តូរប្រាក់ខាងលើនឹងត្រូវបានផ្លាស់ប្តូររៀងរាល់ថ្ងៃធ្វើការតែប៉ុណ្ណោះ។",
    "input: ស្នើសុំកម្ចី",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់កម្ចីយ៉ាងទូលំទូលាយ និងភាពបត់បែនរបស់អតិថិជន។\n\nសូមជ្រើសរើសប្រភេទកម្ចីខាងក្រោម។",
    "input: កំចី",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់កម្ចីយ៉ាងទូលំទូលាយ និងភាពបត់បែនរបស់អតិថិជន។\n\nសូមជ្រើសរើសប្រភេទកម្ចីខាងក្រោម។",
    "input: ស្នើសុំកម្ចីទូទៅ",
    "output: សួស្តីបង! អេ អឹម ខេ ផ្តល់កម្ចីយ៉ាងទូលំទូលាយ និងភាពបត់បែនរបស់អតិថិជន។\n\nសូមជ្រើសរើសប្រភេទកម្ចីខាងក្រោម។",
    "input: កម្ចីអាជីវកម្ម",
    "output: បើបងកំពុងតែស្វែងរកដំណោះស្រាយហិរញ្ញវត្ថុសមស្រប ដើម្បីធ្វើឲ្យអាជី​វកម្មរបស់បងមានការរីកចម្រើនមែនទេ។ អេ អឹម ខេ យល់ពីតម្រូវការរបស់លោកអ្នក និងមានការតាំងចិត្តធ្វើការជាមួយលោកអ្នក ដើម្បីឲ្យអាជីវកម្មមានការរីកចម្រើន។ អេ អឹម ខេ បានបង្កើតផលិតផលកម្ចីជាច្រើនសម្រាប់អាជីវកម្មប្រកបដោយភាពបត់បែន ជាពិសេសជម្រើសក្នុងការបង់សង ដែលត្រូវនឹងអាជីវកម្មរបស់លោកអ្នក។\n\nខាងក្រោមនេះគឺជាប្រភេទផលិតផលកម្ចីអាជីវកម្មមានច្រើនបែប បងអាចជ្រើសរើសតាមប្រភេទអាជីវកម្មរបស់បង។",
    "input: សេវាកម្ចីខ្នាតតូចមធ្បម",
    "output: បើបងកំពុងតែស្វែងរកដំណោះស្រាយហិរញ្ញវត្ថុសមស្រប ដើម្បីធ្វើឲ្យអាជី​វកម្មរបស់បងមានការរីកចម្រើនមែនទេ។ អេ អឹម ខេ យល់ពីតម្រូវការរបស់លោកអ្នក និងមានការតាំងចិត្តធ្វើការជាមួយលោកអ្នក ដើម្បីឲ្យអាជីវកម្មមានការរីកចម្រើន។ អេ អឹម ខេ បានបង្កើតផលិតផលកម្ចីជាច្រើនសម្រាប់អាជីវកម្មប្រកបដោយភាពបត់បែន ជាពិសេសជម្រើសក្នុងការបង់សង ដែលត្រូវនឹងអាជីវកម្មរបស់លោកអ្នក។\n\nខាងក្រោមនេះគឺជាប្រភេទផលិតផលកម្ចីអាជីវកម្មមានច្រើនបែប បងអាចជ្រើសរើសតាមប្រភេទអាជីវកម្មរបស់បង។",
    "input: បាគង",
    "output: សួស្តីបង! អេ អឹម ខេ គឺជាសមាជិកបាគង ដូចនេះបងអាចវេរលុយទៅគ្រប់ស្ថាបនដែលជាសមាជិកបាគងបានទាំងអស់។\nការវេរលុយពីកម្មវីធីធនាគារចល័ត អេ អឹម ខេ ចេញទៅគ្រប់ស្ថាបនគឺមិនគិតថ្លៃសេវានោះទេ។\nការវេរលុយតាមភ្នាក់ងារចេញទៅគ្រប់ស្ថាបនគឺថ្លៃសេវាសមរម្យ។\n\nបើសិនបងមានបញ្ហាបច្ចេកទេសទាក់ទងនឹងសេវាកម្មសូមបងឆាត សរសេរ សួស្តី ហើយចុចយកប៊ូតុង ជួបបុគ្គលិក។",
    "input: ផ្ទេរតាមបាគង",
    "output: សួស្តីបង! អេ អឹម ខេ គឺជាសមាជិកបាគង ដូចនេះបងអាចវេរលុយទៅគ្រប់ស្ថាបនដែលជាសមាជិកបាគងបានទាំងអស់។\nការវេរលុយពីកម្មវីធីធនាគារចល័ត អេ អឹម ខេ ចេញទៅគ្រប់ស្ថាបនគឺមិនគិតថ្លៃសេវានោះទេ។\nការវេរលុយតាមភ្នាក់ងារចេញទៅគ្រប់ស្ថាបនគឺថ្លៃសេវាសមរម្យ។\n\nបើសិនបងមានបញ្ហាបច្ចេកទេសទាក់ទងនឹងសេវាកម្មសូមបងឆាត សរសេរ សួស្តី ហើយចុចយកប៊ូតុង ជួបបុគ្គលិក។",
    "input: ទូទាត់វិក្កយបត្រ",
    "output: ធ្វើឱ្យអតិថិជនកាន់តែមានភាពងាយស្រួលក្នុងការទូទាត់ មិនត្រឹមតែចំណេញពេល និងថវិកា តែប៉ុណ្ណោះទេ ប៉ុន្តែអតិថិជនអាចធ្វើអាជីវកម្មជាមួយដៃគូរបស់ពួកគេមានទំនាក់ទំនងយ៉ាងជិតស្និទ្ធទៀតផង។ អេ អឹម ខេ​ ផ្តល់សេវាទូទាត់ដែលមានភាពងាយស្រួល រហ័ស និងមានសុវត្ថិភាព។ សេវាទាំងនោះរួមមាន៖ សេវាបង់ទឹក-ភ្លើង បង់សំរាម បញ្ចូលលុយទូរស័ព្ទ និងសេវាទូទាត់ផ្សេងទៀត។\nទូទាត់វិក្កយបត្រ\nអតិថិជនអាចប្រើប្រាស់ និងបង់វិក្កយបត្ររបស់ខ្លួនដោយចំណាយពេលត្រឹមតែពីបីនាទីតែប៉ុណ្ណោះតាមរយៈកម្មវិធីធនាគារចល័ត ឬភ្នាក់ងារ អេ អឹម ខេ ទូទាំងប្រទេស។ អេ អឹម ខេ បានចាប់ដៃគូអាជីវកម្មជាច្រើនទូទាំងប្រទេសក្នុងការផ្តល់ជូនសេវាទូទាត់វិក្កយបត្រ។ ខាងក្រោមនេះ គឺជាដៃគូរបស់យើងមួយចំនួន៖​ អគ្គសនីកម្ពុជា រដ្ឋាករទឹកស្វ័យ័តភ្នំពេញ រដ្ឋាករស្វ័យ័តគ្រប់គ្រងសំរាម និងសំណល់រឹងភ្នំពេញ Banhji E-power bill24 ។",
    "input: ទូទាត់",
    "output: ធ្វើឱ្យអតិថិជនកាន់តែមានភាពងាយស្រួលក្នុងការទូទាត់ មិនត្រឹមតែចំណេញពេល និងថវិកា តែប៉ុណ្ណោះទេ ប៉ុន្តែអតិថិជនអាចធ្វើអាជីវកម្មជាមួយដៃគូរបស់ពួកគេមានទំនាក់ទំនងយ៉ាងជិតស្និទ្ធទៀតផង។ អេ អឹម ខេ​ ផ្តល់សេវាទូទាត់ដែលមានភាពងាយស្រួល រហ័ស និងមានសុវត្ថិភាព។ សេវាទាំងនោះរួមមាន៖ សេវាបង់ទឹក-ភ្លើង បង់សំរាម បញ្ចូលលុយទូរស័ព្ទ និងសេវាទូទាត់ផ្សេងទៀត។\nទូទាត់វិក្កយបត្រ\nអតិថិជនអាចប្រើប្រាស់ និងបង់វិក្កយបត្ររបស់ខ្លួនដោយចំណាយពេលត្រឹមតែពីបីនាទីតែប៉ុណ្ណោះតាមរយៈកម្មវិធីធនាគារចល័ត ឬភ្នាក់ងារ អេ អឹម ខេ ទូទាំងប្រទេស។ អេ អឹម ខេ បានចាប់ដៃគូអាជីវកម្មជាច្រើនទូទាំងប្រទេសក្នុងការផ្តល់ជូនសេវាទូទាត់វិក្កយបត្រ។ ខាងក្រោមនេះ គឺជាដៃគូរបស់យើងមួយចំនួន៖​ អគ្គសនីកម្ពុជា រដ្ឋាករទឹកស្វ័យ័តភ្នំពេញ រដ្ឋាករស្វ័យ័តគ្រប់គ្រងសំរាម និងសំណល់រឹងភ្នំពេញ Banhji E-power bill24 ។",
    "input: កម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត",
    "output: សួស្តី! អេ អឹម ខេ ផ្តល់ជូននូវកម្មវិធីធនាគារចល័ត ដែលមានសុវត្ថិភាព ងាយស្រួល និងលឿនរហ័ស ដោយមានមុខងារជាច្រើន ដើម្បីបំពេញសេចក្តីត្រូវការសេវាហិរញ្ញវត្ថុប្រចាំថ្ងៃរបស់លោកអ្នក។ លោកអ្នកពិនិត្យ និងតាមដានសាច់ប្រាក់របស់លោកអ្នកគ្រប់ពេលវេលា។ លោកអ្នកអាចធ្វើការទូទាត់វិក្កយបត្រ ឬផ្ទេរប្រាក់ទៅកាន់មនុស្សជាទីស្រលាញ់ជាមួយនឹងការចុចប៉ុន្មានដងតែប៉ុណ្ណោះ។ បន្ថែមលើនេះ លោកអ្នកអាច​បង្កើតផែនការសន្សំផ្ទាល់ខ្លួនដោយសម្រេចចិត្តថាប្រាក់ប៉ុន្មាន និងរយៈពេលប៉ុណ្ណា ដើម្បីបំពេញផែនការអនាគតរបស់ខ្លួន។",
    "input: ធនាគារចល័ត",
    "output: សួស្តី! អេ អឹម ខេ ផ្តល់ជូននូវកម្មវិធីធនាគារចល័ត ដែលមានសុវត្ថិភាព ងាយស្រួល និងលឿនរហ័ស ដោយមានមុខងារជាច្រើន ដើម្បីបំពេញសេចក្តីត្រូវការសេវាហិរញ្ញវត្ថុប្រចាំថ្ងៃរបស់លោកអ្នក។ លោកអ្នកពិនិត្យ និងតាមដានសាច់ប្រាក់របស់លោកអ្នកគ្រប់ពេលវេលា។ លោកអ្នកអាចធ្វើការទូទាត់វិក្កយបត្រ ឬផ្ទេរប្រាក់ទៅកាន់មនុស្សជាទីស្រលាញ់ជាមួយនឹងការចុចប៉ុន្មានដងតែប៉ុណ្ណោះ។ បន្ថែមលើនេះ លោកអ្នកអាច​បង្កើតផែនការសន្សំផ្ទាល់ខ្លួនដោយសម្រេចចិត្តថាប្រាក់ប៉ុន្មាន និងរយៈពេលប៉ុណ្ណា ដើម្បីបំពេញផែនការអនាគតរបស់ខ្លួន។",
    "input: អេបធនាគារ",
    "output: សួស្តី! អេ អឹម ខេ ផ្តល់ជូននូវកម្មវិធីធនាគារចល័ត ដែលមានសុវត្ថិភាព ងាយស្រួល និងលឿនរហ័ស ដោយមានមុខងារជាច្រើន ដើម្បីបំពេញសេចក្តីត្រូវការសេវាហិរញ្ញវត្ថុប្រចាំថ្ងៃរបស់លោកអ្នក។ លោកអ្នកពិនិត្យ និងតាមដានសាច់ប្រាក់របស់លោកអ្នកគ្រប់ពេលវេលា។ លោកអ្នកអាចធ្វើការទូទាត់វិក្កយបត្រ ឬផ្ទេរប្រាក់ទៅកាន់មនុស្សជាទីស្រលាញ់ជាមួយនឹងការចុចប៉ុន្មានដងតែប៉ុណ្ណោះ។ បន្ថែមលើនេះ លោកអ្នកអាច​បង្កើតផែនការសន្សំផ្ទាល់ខ្លួនដោយសម្រេចចិត្តថាប្រាក់ប៉ុន្មាន និងរយៈពេលប៉ុណ្ណា ដើម្បីបំពេញផែនការអនាគតរបស់ខ្លួន។",
    "input: សេវាទូទាត់រហ័ស",
    "output: “សេវាទូទាត់រហ័ស” ត្រូវបានបង្កើតឡើងដោយធនាគារជាតិនៃកម្ពុជាដែលអាចឲ្យអតិថិជនផ្ទេរ ឬទទួលប្រាក់ទៅវិញទៅមករវាងគ្រឹះស្ថានមីក្រូហិរញ្ញវត្ថុដែលជាសមាជិក។ ជាមួយគ្នានេះផងដែរ អេ អឹម ខេ ផ្តល់សេវាទូទាត់រហ័សតាមរយៈកម្មវិធីធនាគារចល័ត ភ្នាក់ងារ និងការិយាល័យទូទាំងប្រទេសកម្ពុជា។\n\nលក្ខណៈផលិតផល និងអត្ថប្រយោជន៍\n១.​ រូបិយប័ណ្ណ ខ្មែររៀល\n២. ប្រភេទប្រតិបត្តិការ គណនី ទៅ គណនី\n៣. ឯកសារតម្រូវ អតិថិជនត្រូវមានគណនីសន្សំនៅ អេ អឹម ខេ\nបណ្តាញ ទំហំទឹកប្រាក់ និងថ្លៃសេវា នៅ ការិយាល័យ និងកម្មវិធីធនាគារចល័ត អេ អឹម ខេ\n១. តូចជាង ឬស្មើ ៤.០០០.០០០ រៀល ៤.០០០ រៀល\n២. ធំជាង ៤.០០០.១០០ ដល់ ២០.០០០.០០០ រៀល ៨.០០០ រៀល\n៣. ធំជាង ២០.០០០.១០០ ដល់ ៤០.០០០.០០០ រៀល ១២.០០០ រៀល",
    "input: សូមអរគុណ",
    "output: សូមអរគុណ! សម្រាប់ការទាក់ទងមក អេ អឹម ខេ។",
    "input: អរគុណ",
    "output: សូមអរគុណ! សម្រាប់ការទាក់ទងមក អេ អឹម ខេ។",
    "input: អរគុណច្រើន",
    "output: សូមអរគុណ! សម្រាប់ការទាក់ទងមក អេ អឹម ខេ។",
    "input: Hello",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Hey",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Hi",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Hay",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Hallo",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Halo",
    "output: Hello! Welcome AMK Contact Center.\nI am AMK Chatbot💬, anything may I help you?\n(Please press \"Meet Staff\" for other issue)",
    "input: Want to be agent",
    "output: Hello! Thank you for your interest.\nFor condition become AMK Agent are:\n⏱️Have enough time to serve customers.\n📍Convenient location.\n✍️Able to read, write and use smartphones.\n💲Have enough capital.\nFor easily provide you with details, please let me know\n\n📞What is your phone number?",
    "input: Become agent",
    "output: Hello! Thank you for your interest.\nFor condition become AMK Agent are:\n⏱️Have enough time to serve customers.\n📍Convenient location.\n✍️Able to read, write and use smartphones.\n💲Have enough capital.\nFor easily provide you with details, please let me know\n\n📞What is your phone number?",
    "input: Auto Lease",
    "output: Hello! AMK provide customers who wish to have a dream car for personal use in family.\nDo you want for a new car or second hand car (tax or license plate)?",
    "input: Car Lease",
    "output: Hello! AMK provide customers who wish to have a dream car for personal use in family.\nDo you want for a new car or second hand car (tax or license plate)?",
    "input: Active Account",
    "output: Hello! You can request to reactive dormancy account via AMK mobile Banking App.\n\nAre you chatting via AMK Mobile Log in or Non-Log in?",
    "input: Request release inactive account",
    "output: Hello! You can request to reactive dormancy account via AMK mobile Banking App.\n\nAre you chatting via AMK Mobile Log in or Non-Log in?",
    "input: My account inactive how to active?",
    "output: Hello! You can request to reactive dormancy account via AMK mobile Banking App.\n\nAre you chatting via AMK Mobile Log in or Non-Log in?",
    "input: Change Phone",
    "output: Hello! You can request change phone number in your AMK account via online but AMK require you chat through AMK Mobile Banking’s Chat.\n\nAre you chatting on AMK mobile app or Facebook?",
    "input: Request change phone number",
    "output: Hello! You can request change phone number in your AMK account via online but AMK require you chat through AMK Mobile Banking’s Chat.\n\nAre you chatting on AMK mobile app or Facebook?",
    "input: Special A/C",
    "output: Hello! You can request to special account via online. Please send document through chat on AMK mobile app.\n\nAre you chatting via AMK Mobile or Facebook?",
    "input: Special",
    "output: Hello! You can request to special account via online. Please send document through chat on AMK mobile app.\n\nAre you chatting via AMK Mobile or Facebook?",
    "input: Saving",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Fixed",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Future",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Smart kid",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Lucky",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Happy old age",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Hoa",
    "output: Thank for your interesting in our AMK Products and Services. AMK have many saving productions as below:",
    "input: Payroll",
    "output: Thank for your interesting in our AMK payroll service.\n\nWe would like to ask some information about your company.\n\nWhat is contact person's phone number?",
    "input: Payroll Service",
    "output: Thank for your interesting in our AMK payroll service.\n\nWe would like to ask some information about your company.\n\nWhat is contact person's phone number?",
    "input: Insurance",
    "output: Hello! Thank you for your interesting in our insurance product.\n\nThere are two insurance product that sell under AMK as below:\n\n1. Health Insurance Product\n\n2. Dai-Ichi Life Insurance\n\nWhich one do you like?",
    "input: Working Hour",
    "output: Thank you for your interesting in AMK.\n\nAMK office working day and hour is from 8:00 AM to 3:30 PM, Monday to Friday (excluding National Day).",
    "input: Job Opportunity",
    "output: For Job Opportunity please click this link:\nhttps://www.amkcambodia.com/en/careers/\n\nTo apply any job: please send your CV and Cover Letter stating the section or role you are interested in to the following channels:\n\nEmail: job@amkcambodia.com;\nTelegram: https://t.me/Amkcambodia;\nInbox to AMK MFI (AMK Facebook Messenger) or AMK Career.",
    "input: Job",
    "output: For Job Opportunity please click this link:\nhttps://www.amkcambodia.com/en/careers/\n\nTo apply any job: please send your CV and Cover Letter stating the section or role you are interested in to the following channels:\n\nEmail: job@amkcambodia.com;\nTelegram: https://t.me/Amkcambodia;\nInbox to AMK MFI (AMK Facebook Messenger) or AMK Career.",
    "input: Office Location",
    "output: Thank you for your interesting in AMK.\n\nPlease visit our website for AMK’s location\nby click this link https://www.amkcambodia.com/en/contact-us/\n\nAnd you will be able to find AMK ATM or AMK Office",
    "input: AMK ATM",
    "output: Thank you for your interesting in AMK.\n\nPlease visit our website for AMK’s location\nby click this link https://www.amkcambodia.com/en/contact-us/\n\nAnd you will be able to find AMK ATM or AMK Office",
    "input: Merchant",
    "output: Hello! AMK Merchant is refers to a partner who allows a customer to pay for their goods/services by scanning AMK's KHQR from any bank app. If you want to become an AMK Merchant, please some your information such as: Please give me your phone number!",
    "input: AMK Card",
    "output: AMK’s clients can access their accounts at any time using any of our Express banking services (ATM/CDM) with a single AMK card. Moreover, AMK’s clients can enjoy discounts with AMK’s merchants across the country. AMK’s offer 3 different type of cards.",
    "input: Card",
    "output: AMK’s clients can access their accounts at any time using any of our Express banking services (ATM/CDM) with a single AMK card. Moreover, AMK’s clients can enjoy discounts with AMK’s merchants across the country. AMK’s offer 3 different type of cards.",
    "input: Money Transfer",
    "output: Hello! You can transfer money through AMK both Local and International.\n\nDo you want to know about local or international money transfer service?",
    "input: Transfer",
    "output: Hello! You can transfer money through AMK both Local and International.\n\nDo you want to know about local or international money transfer service?",
    "input: Exchange Rate",
    "output: Hello! AMK exchange rates are subject to change on a regular basis during business hour. If you want to know the exchange rate of the previous day, please click link for more detail: https://www.amkcambodia.com/en/exchange-rate/\n\nNote:\n-The above rates are updated on every working day only.\n-The rates are quoted for indication purpose only and subject to variation",
    "input: Foreign exchange rate",
    "output: Hello! AMK exchange rates are subject to change on a regular basis during business hour. If you want to know the exchange rate of the previous day, please click link for more detail: https://www.amkcambodia.com/en/exchange-rate/\n\nNote:\n-The above rates are updated on every working day only.\n-The rates are quoted for indication purpose only and subject to variation",
    "input: General Loan",
    "output: Hello! AMK offers a wide range of loans and customer flexibility. Please choose the following type of loan.",
    "input: Bakong",
    "output: Hello! AMK is a member of bakong so you transfer to all bank member of bakong.\nAll Transaction Transfer/Scan from AMK to other bank by AMK Mobile Banking is free of charge.\nAll Transaction Transfer/Scan from AMK to other bank by AMK Agent are reasonable charge fee.\n\nIf you got issue relating to transaction of bakong please chat us via AMK Mobile Banking App by write Hello and then click button Meet Staff.",
    "input: Bakong Service",
    "output: Hello! AMK is a member of bakong so you transfer to all bank member of bakong.\nAll Transaction Transfer/Scan from AMK to other bank by AMK Mobile Banking is free of charge.\nAll Transaction Transfer/Scan from AMK to other bank by AMK Agent are reasonable charge fee.\n\nIf you got issue relating to transaction of bakong please chat us via AMK Mobile Banking App by write Hello and then click button Meet Staff.",
    "input: Payment Service",
    "output: Bring payment close to the customer with a simple step to complete is not only help the customer to save their time and money but also support our partner to stay connect with their customer all the time. AMK officer wide range of payment services such as bill payment (i.e., electricity, water, waste, etc…), phone top up, etc.\n\nCustomer can utilize and pay their bill at their figure tip thought our Mobile Banking App or just few steps away with our Agent Banking across Cambodia. AMK is working with over few hundred payment partners across Cambodia. Below are few partners: EDC, PPWSA, PPSWMA, Banhji, E-power, Bill24",
    "input: ",
    "output: AMK offers a secure, easy to use Mobile Banking Application with many features to meet your day to day needs. You can check and monitor your money at any time. You can make all necessary bill payments or fund transfers to your loved ones with a few taps of your fingers. Moreover, you can create your own savings plan, deciding how much money and how long, to meet your future plans.",
    "input: AMK Mobile Banking App",
    "output: AMK offers a secure, easy to use Mobile Banking Application with many features to meet your day to day needs. You can check and monitor your money at any time. You can make all necessary bill payments or fund transfers to your loved ones with a few taps of your fingers. Moreover, you can create your own savings plan, deciding how much money and how long, to meet your future plans.",
    "input: Selfie Banking",
    "output: AMK offers a secure, easy to use Mobile Banking Application with many features to meet your day to day needs. You can check and monitor your money at any time. You can make all necessary bill payments or fund transfers to your loved ones with a few taps of your fingers. Moreover, you can create your own savings plan, deciding how much money and how long, to meet your future plans.",
    "input: Loyalty Point",
    "output: AMK offers a secure, easy to use Mobile Banking Application with many features to meet your day to day needs. You can check and monitor your money at any time. You can make all necessary bill payments or fund transfers to your loved ones with a few taps of your fingers. Moreover, you can create your own savings plan, deciding how much money and how long, to meet your future plans.",
    "input: Thank You",
    "output: Thank you for you contacting to AMK have a nice day.",
    "input: Thanks",
    "output: Thank you for you contacting to AMK have a nice day.",
    "input: Thank you a lot",
    "output: Thank you for you contacting to AMK have a nice day.",
    f"input: {prompt}",
    "output: ",
  ],
  
  safety_settings=safety_settings                                  
                                    )
  return response



def prompt_category(prompt):

  response = model.generate_content([
    "input: សួស្តី",
    "output: សួស្តី",
    "input: ហេ",
    "output: សួស្តី",
    "input: ហាឡូ",
    "output: សួស្តី",
    "input: ហាយ",
    "output: សួស្តី",
    "input: ចង់ក្លាយជាភ្នាក់ងារ",
    "output: ចង់ក្លាយជាភ្នាក់ងារ",
    "input: ក្លាយជាភ្នាក់ងារ",
    "output: ចង់ក្លាយជាភ្នាក់ងារ",
    "input: ចង់បង់រំលស់ឡាន",
    "output: ចង់បង់រំលស់ឡាន",
    "input: ចង់ទិញឡានបង់រំលស់",
    "output: ចង់បង់រំលស់ឡាន",
    "input: ម៉ូតូអគ្គសនី",
    "output: ចង់បង់រំលស់ឡាន",
    "input: ឡានអគ្គសនី",
    "output: ចង់បង់រំលស់ឡាន",
    "input: ឡជីឧស្ម័ន",
    "output: ចង់បង់រំលស់ឡាន",
    "input: ទិញសូឡា",
    "output: ចង់បង់រំលស់ឡាន",
    "input: បើកដំណើរការគណនី",
    "output: បើកដំណើរការគណនី",
    "input: គណនីអសកម្ម",
    "output: បើកដំណើរការគណនី",
    "input: ចង់ផ្លាស់ប្តូរលេខទូរស័ព្ទ",
    "output: ចង់ផ្លាស់ប្តូរលេខទូរស័ព្ទ",
    "input: ចង់ប្តូរលេខទូរស័ព្ទព្រោះបាត់លេខចាស់",
    "output: ចង់ផ្លាស់ប្តូរលេខទូរស័ព្ទ",
    "input: ស្នើសុំលេខគណនីពិសេស",
    "output: ស្នើសុំលេខគណនីពិសេស",
    "input: ចង់ប្តូរលេខពិសេសេ",
    "output: ស្នើសុំលេខគណនីពិសេស",
    "input: សន្សំប្រាក់",
    "output: សន្សំប្រាក់",
    "input: សន្សំសំចៃ",
    "output: សន្សំប្រាក់",
    "input: គណនីសន្សំ",
    "output: សន្សំប្រាក់",
    "input: សន្សំលុយ",
    "output: សន្សំប្រាក់",
    "input: បើកប្រាក់ខែ",
    "output: បើកប្រាក់ខែ",
    "input: សេវាបើកប្រាក់បៀវត្ស",
    "output: បើកប្រាក់ខែ",
    "input: ធានារ៉ាប់រង់",
    "output: ធានារ៉ាប់រង់",
    "input: ចង់ទិញធានារ៉ាប់រង់",
    "output: ធានារ៉ាប់រង់",
    "input: ធានារ៉ាប់រង់អាយុជីវិត",
    "output: ធានារ៉ាប់រង់",
    "input: ធានារ៉ាប់ខ្នាតតូច",
    "output: ធានារ៉ាប់រង់",
    "input: ម៉ោងធ្វើការ",
    "output: ម៉ោងធ្វើការ",
    "input: តើម៉ោងធ្វើការអេអឹមខេពេលណាខ្លះ",
    "output: ម៉ោងធ្វើការ",
    "input: ដាក់ពាក្យធ្វើការ",
    "output: ដាក់ពាក្យធ្វើការ",
    "input: ឱកាសការងារ",
    "output: ដាក់ពាក្យធ្វើការ",
    "input: ទីតាំងអេអឹមខេ",
    "output: ទីតាំងអេអឹមខេ",
    "input: ទីតាំងការិយាល័យ",
    "output: ទីតាំងអេអឹមខេ",
    "input: ទីតាំងម៉ាស៊ីន អេ ធី អឹម",
    "output: ទីតាំងអេអឹមខេ",
    "input: ទីតាំងម៉ាស៊ីន ATM",
    "output: ទីតាំងអេអឹមខេ",
    "input: ដៃគូអាជីវកម្ម",
    "output: ដៃគូអាជីវកម្ម",
    "input: កាត",
    "output: កាត",
    "input: អេអឹមខេកាត",
    "output: កាត",
    "input: កាតអេអឹមខេ",
    "output: កាត",
    "input: វេរលុយ",
    "output: វេរលុយ",
    "input: ផ្ទេរប្រាក់",
    "output: វេរលុយ",
    "input: ផ្ទេរ",
    "output: វេរលុយ",
    "input: អត្រារប្តូរ",
    "output: អត្រារប្តូរ",
    "input: ស្នើសុំកម្ចី",
    "output: ស្នើសុំកម្ចី",
    "input: កំចី",
    "output: ស្នើសុំកម្ចី",
    "input: ស្នើសុំកម្ចីទូទៅ",
    "output: ស្នើសុំកម្ចី",
    "input: កម្ចីអាជីវកម្ម",
    "output: SME Loan",
    "input: សេវាកម្ចីខ្នាតតូចមធ្បម",
    "output: SME Loan",
    "input: បាគង",
    "output: បាគង",
    "input: ផ្ទេរតាមបាគង",
    "output: បាគង",
    "input: ទូទាត់វិក្កយបត្រ",
    "output: ទូទាត់វិក្កយបត្រ",
    "input: ទូទាត់",
    "output: ទូទាត់វិក្កយបត្រ",
    "input: កម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត",
    "output: កម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត",
    "input: ធនាគារចល័ត",
    "output: កម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត",
    "input: អេបធនាគារ",
    "output: កម្មវិធីទូរស័ព្ទដៃធនាគារចល័ត",
    "input: សេវាទូទាត់រហ័ស",
    "output: សេវាទូទាត់រហ័ស",
    "input: សូមអរគុណ",
    "output: សូមអរគុណ",
    "input: អរគុណ",
    "output: សូមអរគុណ",
    "input: អរគុណច្រើន",
    "output: សូមអរគុណ",
    "input: Hello",
    "output: Hi",
    "input: Hey",
    "output: Hi",
    "input: Hi",
    "output: Hi",
    "input: Hay",
    "output: Hi",
    "input: Hallo",
    "output: Hi",
    "input: Halo",
    "output: Hi",
    "input: Want to be agent",
    "output: Want to be agent",
    "input: Become agent",
    "output: Want to be agent",
    "input: Auto Lease",
    "output: Auto Lease",
    "input: Car Lease",
    "output: Auto Lease",
    "input: Active Account",
    "output: Active Account",
    "input: Request release inactive account",
    "output: Active Account",
    "input: My account inactive how to active?",
    "output: Active Account",
    "input: Change Phone",
    "output: Change Phone",
    "input: Request change phone number",
    "output: Change Phone",
    "input: Special A/C",
    "output: Special",
    "input: Special",
    "output: Special",
    "input: Saving",
    "output: Saving",
    "input: Fixed",
    "output: Saving",
    "input: Future",
    "output: Saving",
    "input: Smart kid",
    "output: Saving",
    "input: Lucky",
    "output: Saving",
    "input: Happy old age",
    "output: Saving",
    "input: Hoa",
    "output: Saving",
    "input: Payroll",
    "output: Payroll",
    "input: Payroll Service",
    "output: Payroll",
    "input: Insurance",
    "output: Insurance",
    "input: Working Hour",
    "output: Working Hour",
    "input: Job Opportunity",
    "output: Job",
    "input: Job",
    "output: Job",
    "input: Office Location",
    "output: Location",
    "input: AMK ATM",
    "output: Location",
    "input: Merchant",
    "output: Want to be merchant",
    "input: AMK Card",
    "output: AMK Card",
    "input: Card",
    "output: AMK Card",
    "input: Money Transfer",
    "output: Money Transfer",
    "input: Transfer",
    "output: Transfer",
    "input: Exchange Rate",
    "output: Exchange Rate",
    "input: Foreign exchange rate",
    "output: Exchange Rate",
    "input: General Loan",
    "output: Loan",
    "input: Bakong",
    "output: Bakong",
    "input: Bakong Service",
    "output: Bakong",
    "input: Payment Service",
    "output: Payment Service",
    "input: Mobile Banking App",
    "output: Mobile Banking",
    "input: AMK Mobile Banking App",
    "output: Mobile Banking",
    "input: Selfie Banking",
    "output: Mobile Banking",
    "input: Loyalty Point",
    "output: Mobile Banking",
    "input: Thank You",
    "output: Thank You",
    "input: Thanks",
    "output: Thank You",
    "input: Thank you a lot",
    "output: Thank You",
    f"input: {prompt}",
    "output: ",
    
  ],
  
  safety_settings=safety_settings)
  return response



def prompt_correction(prompt):

  model = genai.GenerativeModel(
    model_name="gemini-2.0-flash-exp",
    generation_config=generation_config,
    system_instruction="for every input i give to you, return the corrected form of spelling for any typo and misspelling while also correcting potential grammatical error. the input may be english or khmer or a mix of the two but do the same thing for all of the scenario.",
  )
  response = model.generate_content(prompt)
  return response.text
